language: python
dist: trusty
sudo: false

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.8-dev
  - pypy
  - pypy3

env:
  global:
    - LIBXSLT_VERSION=1.1.32
  matrix:
    - STATIC_DEPS=true
    - STATIC_DEPS=false

matrix:
  include:
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # travis-ci/travis-ci#9069
      env: STATIC_DEPS=true
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # travis-ci/travis-ci#9069
      env: STATIC_DEPS=false

install:
    - pip install -U pip wheel
    - pip install $(if [ -z "${TRAVIS_PYTHON_VERSION##*-dev}" ]; then echo "--install-option=--no-cython-compile"; fi ) -r requirements.txt
    - pip install -U beautifulsoup4 cssselect html5lib

script:
  - CFLAGS="-O0 -g -fPIC" python -u setup.py build_ext --inplace $(if [ -n "${TRAVIS_PYTHON_VERSION##2.*}" -a -n "${TRAVIS_PYTHON_VERSION##3.[34]*}" ]; then echo -n " -j7 "; fi )
  - CFLAGS="-O0 -g -fPIC" PYTHONUNBUFFERED=x make test

matrix:
  allow_failures:
    - python: 3.8-dev
    - python: pypy
    - python: pypy3

cache:
  pip: true
